name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Black
        uses: "Unholster/black-action-test@master"
        with:
          args: --verbose --check .
