on: pull_request
name: auto-format
jobs:
  lint:
    name: Black Code Formatter
    runs-on: ubuntu-latest
    steps:
    - name: Black Code Formatter
      uses: Unholster/action-black@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BLACK_ARGS: "."